# Generated by Django 5.1.3 on 2024-12-05 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
